#!/bin/sh
 
ssh kennytaht45@thegocostaging.com <<EOF
  cd ~/public_html/karma/staging/karma_oc/
  git fetch
  git pull origin staging
  git checkout staging
  cd ~/public_html/karma/staging/karma_of_vancouver/
  git fetch
  git pull origin staging
  git checkout staging
  exit
EOF
